// <auto-generated />
namespace eTrener.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeMealModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeMealModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201705261358094_changeMealModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
