// <auto-generated />
namespace eTrener.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class abcj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abcj));
        
        string IMigrationMetadata.Id
        {
            get { return "201705122031482_abcj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
