// <auto-generated />
namespace eTrener.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changesintraininglog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesintraininglog));
        
        string IMigrationMetadata.Id
        {
            get { return "201705131531414_'changes in training log'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
