// <auto-generated />
namespace eTrener.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changenamesoftablesandviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changenamesoftablesandviews));
        
        string IMigrationMetadata.Id
        {
            get { return "201704291627242_change names of tables and views"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
